---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "spring-boot.fullname" . }}-kong-ingress
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/override: {{ include "spring-boot.fullname" . }}-kongingress
    configuration.konghq.com: {{ include "spring-boot.fullname" . }}-kongingress
  labels:
    {{- include "spring-boot.labels" . | nindent 4 }}
spec:
  rules:
    - host: {{ include "spring-boot.fullname" . }}.istio.dev1.eks.openshiftlabs.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "spring-boot.fullname" . }}
                port:
                  number: 8080
          - path: /actuator
            pathType: Prefix
            backend:
              service:
                name: {{ include "spring-boot.fullname" . }}
                port:
                  number: 8080
---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: {{ include "spring-boot.fullname" . }}-kongingress
  labels:
    {{- include "spring-boot.labels" . | nindent 4 }}
route:
  preserve_host: false
upstream:
  host_header: {{ include "spring-boot.fullname" . }}.{{ .Release.Namespace }}.svc
