# For general lifecycle information see https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html

# This template will build and test your projects
# * Caches downloaded dependencies and plugins between invocation.
# * Verify but don't deploy merge requests.
# * Deploy built artifacts from main branch only.

variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

  DOCKER_REGISTRY: 005459661421.dkr.ecr.eu-west-2.amazonaws.com
  AWS_DEFAULT_REGION: eu-west-2
  APP_NAME: heroes-service
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

image: maven:3-jdk-11

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository
  key: "$CI_JOB_NAME"

package:jdk11:
  stage: build
  artifacts:
    paths:
      - target/*.jar
  script:
    - 'mvn $MAVEN_CLI_OPTS package -DskipTests'
  only:
    - main

docker-build-main:
  # Official docker image.
  image: docker:latest
  stage: deploy
  services:
    - docker:dind
  before_script:
    - apk add --no-cache curl jq python3 py3-pip
    - pip install awscli
    - aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    - aws --version
    - docker info
    - docker --version
  script:
    - docker build --pull -t $DOCKER_REGISTRY/$APP_NAME:$CI_COMMIT_REF_SLUG .
    - docker push $DOCKER_REGISTRY/$APP_NAME:$CI_COMMIT_REF_SLUG
    - docker tag $DOCKER_REGISTRY/$APP_NAME:$CI_COMMIT_REF_SLUG $DOCKER_REGISTRY/$APP_NAME:latest
    - docker push $DOCKER_REGISTRY/$APP_NAME:latest
  only:
    - main

docker-build:
  # Official docker image.
  image: docker:latest
  stage: deploy
  services:
    - docker:dind
  before_script:
    - apk add --no-cache curl jq python3 py3-pip
    - pip install awscli
    - aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    - aws --version
    - docker info
    - docker --version
  script:
    - docker build --pull -t $DOCKER_REGISTRY/$APP_NAME:$CI_COMMIT_REF_SLUG .
    - docker push $DOCKER_REGISTRY/$APP_NAME:$CI_COMMIT_REF_SLUG
    - docker tag $DOCKER_REGISTRY/$APP_NAME:$CI_COMMIT_REF_SLUG $DOCKER_REGISTRY/$APP_NAME:SNAPSHOT
    - docker push $DOCKER_REGISTRY/$APP_NAME:SNAPSHOT
  except:
    - main