# Set how many application instances to run.
replicaCount: 1

# Override these settings and use your container image.
image:
  repository: 005459661421.dkr.ecr.eu-west-2.amazonaws.com/heroes-service
  tag: latest
  pullPolicy: IfNotPresent

# Set image pull secrets (in case you're using a private container registry).
imageCredentials:
  registry: # gcr.io
  username: # oauth2accesstoken
  password: # $(gcloud auth print-access-token)

# Set service type: LoadBalancer, ClusterIP, NodePort
service:
  type: LoadBalancer
  port: 8080

ingressBase: dev1.eks.openshiftlabs.net
ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: spring-boot
      paths: ["/"]
  tls: []

# Set to false to disable Prometheus support.
monitoring: true

# Set to false to disable Spring Cloud Kubernetes support.
sck: true

# Set configuration properties.
config:
  foo: bar
