# Set how many application instances to run.
replicaCount: 1

# Override these settings and use your container image.
image:
  repository: 005459661421.dkr.ecr.eu-west-2.amazonaws.com/heroes-service
  tag: latest
  pullPolicy: IfNotPresent

# Set image pull secrets (in case you're using a private container registry).
imageCredentials:
  registry: # gcr.io
  username: # oauth2accesstoken
  password: # $(gcloud auth print-access-token)

# Set service type: LoadBalancer, ClusterIP, NodePort
service:
  type: LoadBalancer
  port: 8080

ingressBase: dev1.eks.openshiftlabs.net
ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: spring-boot
      paths: ["/"]
  tls: []

# Set to false to disable Prometheus support.
monitoring: true

# Set to false to disable Spring Cloud Kubernetes support.
sck: true

# Set configuration properties.
config:
  foo: bar

tower:
  useOldRolloutMethod: false

extraVarsFiles: {}
  # - name: heroes_target.yaml
  #   value: |-
  #     prometheus_target_service: "heroes_app_eks"
  #     prometheus_target_env: "dev"
  #     prometheus_target_targets:
  #       - "kong-heroes-dev.istio.dev1.eks.openshiftlabs.net"

  # - name: heroes_curses_rule.yaml
  #   value: |-
  #     prometheus_rules_alert_group: "heroes_app_eks"
  #     prometheus_rules_alert_name: "fight_curses_total_eks"
  #     prometheus_rules_alert_expr: "fight_curses_total{service='heroes_app_eks'} > 10"
  #     prometheus_rules_alert_for: "1m"
  #     prometheus_rules_alert_severity: "warning"
  #     prometheus_rules_alert_annotation_title: "Example application counter and threshold"
  #     prometheus_rules_alert_annotation_description: "Example application counter and threshold"

  # - name: heroes_punches_rule.yaml
  #   value: |-
  #     prometheus_rules_alert_group: "heroes_app_eks"
  #     prometheus_rules_alert_name: "fight_punches_total_eks"
  #     prometheus_rules_alert_expr: "fight_punches_total{service='heroes_app_eks'} > 10"
  #     prometheus_rules_alert_for: "1m"
  #     prometheus_rules_alert_severity: "warning"
  #     prometheus_rules_alert_annotation_title: "Example application counter and threshold"
  #     prometheus_rules_alert_annotation_description: "Example application counter and threshold"

  # - name: heroes_kicks_rule.yaml
  #   value: |-
  #     prometheus_rules_alert_group: "heroes_app_eks"
  #     prometheus_rules_alert_name: "fight_kicks_total_eks"
  #     prometheus_rules_alert_expr: "fight_kicks_total{service='heroes_app_eks'} > 10"
  #     prometheus_rules_alert_for: "1m"
  #     prometheus_rules_alert_severity: "warning"
  #     prometheus_rules_alert_annotation_title: "Example application counter and threshold"
  #     prometheus_rules_alert_annotation_description: "Example application counter and threshold"
